name: CI

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create new release for Ubuntu 22.04 with CUDA"
        required: true
        type: boolean

jobs:
  ubuntu-22_04-cmake:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zip wget gnupg

      - name: Install CUDA 12.2
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-archive-keyring.gpg
          sudo mv cuda-archive-keyring.gpg /usr/share/keyrings/
          sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /" > /etc/apt/sources.list.d/cuda.list'
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-2

      - name: Build with CUDA
        run: |
          mkdir build
          cd build
          cmake .. -DSD_CUDA=ON -DSD_BUILD_SHARED_LIBS=ON
          cmake --build . --config Release -j$(nproc)

      - name: Pack artifacts
        run: |
          cp ggml/LICENSE ./build/bin/ggml.txt
          cp LICENSE ./build/bin/stable-diffusion.cpp.txt
          zip -j sd-ubuntu22.04-cuda-bin.zip ./build/bin/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sd-ubuntu22.04-cuda-bin.zip
          path: sd-ubuntu22.04-cuda-bin.zip
